sudo: required
language: elixir
notifications:
  - email: false
services:
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  - export BRANCH=$(echo "${TRAVIS_BRANCH//'/'/-}")
  - export VERSION=$(cat mix.exs | grep version | sed "s/.*\"\(.*\)\".*/\1/")
before_script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - chmod +x ./scripts/*
  - ./scripts/build.sh
script:
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml run jesse-hosted-test mix test
deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh ${DOCKER_USER} ${DOCKER_PASSWORD} ${CONTAINER_IMAGE} ${DOCKER_REPO} ${BRANCH} ${VERSION}
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh ${DOCKER_USER} ${DOCKER_PASSWORD} ${CONTAINER_IMAGE} ${DOCKER_REPO} ${BRANCH} ${VERSION}
    on:
      branch: master