version: '3.4'
services:
  jesse-hosted-test:
    build: 
      context: .
      args:
        - MIX_ENV=test
        - GCP_JSON=${GOOGLE_APPLICATION_CREDENTIALS}
    image: jesse-hosted-test
    ports:
      - 5000:80